Внесла фамилию с ссылкой
htmlacademy-htmlcss/1515611-sedona-36 pull request #1
Opened 2023-01-18 19:30 UTC by AleCherkas

2023-01-19 05:55 UTC, pavel-nyukalo requested changes

2023-01-19 05:55 UTC, pavel-nyukalo commented on Readme.md
> +* Наставник: `Павел Нюкало (https://htmlacademy.ru/profile/id869225)`.
Здесь у нас используется синтаксис `markdown`, поэтому очень важно его соблюдать

Для ссылок в `markdown` используется следующий синтаксис - `[Текст ссылки](сама ссылка)` (без пробелов между скобками)

Иначе ссылка выглядит вот так

![image](https://user-images.githubusercontent.com/52506235/213366441-90aab5e4-e39a-413c-b26b-7f57cf2e49d7.png)

2023-01-19 06:32 UTC, AleCherkas commented on Readme.md
> +* Наставник: `Павел Нюкало (https://htmlacademy.ru/profile/id869225)`.
Ага, спасибо, понятно)

2023-01-25 19:22 UTC, AleCherkas commented on Readme.md
> +* Наставник: `Павел Нюкало (https://htmlacademy.ru/profile/id869225)`.
Изменения внесены)

2023-01-26 11:30 UTC, pavel-nyukalo approved these changes

2023-01-26 11:31 UTC, merged