Сделала разметку Седоны
htmlacademy-htmlcss/1515611-sedona-36 pull request #2
Opened 2023-01-28 14:05 UTC by AleCherkas

2023-01-29 17:42 UTC, pavel-nyukalo requested changes

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +          <li class="navigation-item">Гостиницы<a class="navigation-link" href="#"></a></li>
В ссылку нужно обернуть текст, чтобы можно было кликнуть по нему

```html
<li class="navigation-item"><a class="navigation-link" href="#">Главная</a></li>
```

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +        <a class="navigation-link-2" href="#"><span class="visually-hidden">Поиск</span></a>
Для скрытых подписей по критерию нужно добавлять точку в конец. Относится ко всем

![image](https://user-images.githubusercontent.com/52506235/215344928-93016c23-aaa3-41bb-b343-b1c990ee08db.png)

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +        <img src="#" alt="Sedona's mountains">
Горы сделаем фоном, из разметки давай удалим

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +          </li>
В этот (и с мостом) `li` нужно добавить картинки, они контентные

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +        <img src="#" alt="Мост дъявола">
А вот они. В общем, их нужно перенести в соответствующие `li`

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +          <p>Приезжайте в Седону отдохнуть в комфорте и уюте!</p>
Тут немного отступы поехали, нужно будет поправить и проверить по всему файлу. У нас должны использоваться 2 пробела, для отделения вложенных тегов

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +          <a href="#" class="button button-all-hotels">Поиск гостиницы в Седоне</a>
Я бы это в отдельную секцию вынес. Стилизовать будет проще

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +      </section>
Эту секцию кстати можно в футер вынести, она на обоих страницах повторяется

2023-01-29 17:42 UTC, pavel-nyukalo commented on index.html
> +      </nav>
1. Навигация тут уже не нужна на мой взгляд
2. Так же про текст в ссылки
3. Телефон по критерию у нас должен быть размечен ссылкой, с [соответствующим](https://htmlacademy.ru/blog/html/mailto) `href`
4. С `visually-hidden` аккуратнее - он у нас будет скрывать элементы. А ссылки должны быть видимыми

2023-01-30 17:53 UTC, pavel-nyukalo requested changes

2023-01-30 17:53 UTC, pavel-nyukalo commented on index.html
> +        </ul>
Немного отступы нужно допоправить

![image](https://user-images.githubusercontent.com/52506235/215553557-9b883605-f50a-4249-bd8f-c129efc3471a.png)

Должно получиться так
```html
...
<h2 class="visually-hidden">Услуги Седоны.</h2>
<p>Приезжайте в Седону отдохнуть в комфорте и уюте!</p>
<p>Опытный персонал и качественное обслуживание!</p>
<ul class="services-list">
  <li class="services-item">
    <h3>Жилье</h3>
    <p>Рекомендуем пожить в настоящем мотеле,всё как в кино!</p>
  </li>
  <li class="services-item">
    <h3>Еда</h3>
    <p>Всегда заказывайте топовый фирменный бургер, вы не разочаруетесь!</p>
  </li>
  <li class="services-item">
    <h3>Сувениры</h3>
    <p>Не только китайского,но и настоящего местного производства!</p>
  </li>
</ul>
        
     ...
```

2023-01-30 17:53 UTC, pavel-nyukalo commented on index.html
> +          <h3 class="visually-hidden">Покупка тура.</h3>
1. Секция уже хорошо, но давай ее вынесем из родительской секции (и заголовок на h2 поменяется в таком случае)

```html
<section class="services">
  <h2 class="visually-hidden">Услуги Седоны.</h2>
  <p>Приезжайте в Седону отдохнуть в комфорте и уюте!</p>
  <p>Опытный персонал и качественное обслуживание!</p>
  <ul class="services-list">
    <li class="services-item">
      <h3>Жилье</h3>
      <p>Рекомендуем пожить в настоящем мотеле,всё как в кино!</p>
      </li>
    <li class="services-item">
      <h3>Еда</h3>
      <p>Всегда заказывайте топовый фирменный бургер, вы не разочаруетесь!</p>
      </li>
    <li class="services-item">
      <h3>Сувениры</h3>
      <p>Не только китайского,но и настоящего местного производства!</p>
      </li>
  </ul>
</section>

<section>
  <h2 class="visually-hidden">Покупка тура.</h2>
  <p>Заинтересовались?</p>
  <p>Укажите предполагаемые даты поездки,и мы покажем вам лучшие предложения гостиниц в Седоне</p>
  <a href="#" class="button button-all-hotels">Поиск гостиницы в Седоне</a>
</section>
```
2. Отступы. Кстати, если работаешь в vscode, можешь вызвать палитру команд Ctrl Shift P -> format document (если стоит притиер, то лучше не им, а `format document with...`)

![image](https://user-images.githubusercontent.com/52506235/215554127-2faec066-9e77-4bfa-8a15-05c8e74e78ad.png)

![image](https://user-images.githubusercontent.com/52506235/215554156-27ef15ad-29a5-4fdb-bc8d-00b861f8fd00.png)

2023-01-30 17:53 UTC, pavel-nyukalo commented on index.html
>      </section>
Тоже с отступами немного (форматирование должно помочь)

![image](https://user-images.githubusercontent.com/52506235/215554810-cff00f83-13a7-4a34-adf6-a681f62b9f49.png)

Должно получиться
```html
<footer class="page-footer">
  <section>
    <h2 class="visually-hidden">Подписка.</h2>
    <p>Подпишитесь на рассылку</p>
    <p>Только полезная информация и никакого спама, честное бойскаутское!</p>
    <form class="subscription" action="https://echo.htmlacademy.ru/" method="post">
      <label for="email-input" class="visually-hidden">Подписка</label>
      <input type="email" id="email-input" placeholder="Ваш e-mail" required>
      <button class="button" type="submit">Подписаться</button>
    </form>
  </section>
  <section class="footer-contacts">
    <h2 class="visually-hidden">Контакты.</h2>
      <ul>
        <li><a href="https://vk.com/htmlacademy">VK.</a></li>
        <li><a href="https://t.me/htmlacademy">Telegram.</a></li>
        <li><a href="https://www.youtube.com/user/htmlacademyru">Youtube.</a></li>
      </ul>
      <a href="tel:+78128121212">+7(812) 812-12-12</a>
      <a href="https://htmlacademy.ru/">HTML-academy logo</a>
  </section>
</footer>
```

И не забудь убрать `visually-hidden` с ссылок соц. сетей. Они должны быть видимыми. А вот на `label` можно добавить как раз

2023-01-31 14:56 UTC, AleCherkas commented on index.html
> +          <h3 class="visually-hidden">Покупка тура.</h3>
Паш,  а поясни, почему Prettier лучше заменить на HLF ?

2023-02-01 08:22 UTC, pavel-nyukalo commented on index.html
> +          <h3 class="visually-hidden">Покупка тура.</h3>
Prettier довольно сложно настроить для форматирования верстки, так как нам нужно. Например, он ставит `/` в одиночные теги - `<img />, <input />` и тд

А нам по кодгайду академии это не нужно

2023-02-01 08:22 UTC, pavel-nyukalo approved these changes

2023-02-01 08:22 UTC, merged